import { v4 as uuidv4 } from 'uuid';


export const historyData = [
    {
        id: uuidv4(),
        name: 'Some one with a good name',
        description: 'This is a transcation from from some day',
        items: 10,
        length: 5,
        unitPrice: 100,
        cost: 3000,
        date: new Date().toDateString(),
        time: (new Date()).toLocaleTimeString(),
    },
    {
        id: uuidv4(),
        name: 'Some one with a good name',
        description: 'This is a transcation from from some day',
        items: 10,
        length: 5,
        unitPrice: 100,
        cost: 3000,
        date: new Date().toDateString(),
        time: (new Date()).toLocaleTimeString(),
    },
    {
        id: uuidv4(),
        name: 'Some one with a good name',
        description: 'This is a transcation from from some day',
        items: 10,
        length: 5,
        unitPrice: 100,
        cost: 3000,
        date: new Date().toDateString(),
        time: (new Date()).toLocaleTimeString(),
    },
    {
        id: uuidv4(),
        name: 'Some one with a good name',
        description: 'This is a transcation from from some day',
        items: 10,
        length: 5,
        unitPrice: 100,
        cost: 3000,
        date: new Date().toDateString(),
        time: (new Date()).toLocaleTimeString(),
    },
    {
        id: uuidv4(),
        name: 'Some one with a good name',
        description: 'This is a transcation from from some day',
        items: 10,
        length: 5,
        unitPrice: 100,
        cost: 3000,
        date: new Date().toDateString(),
        time: (new Date()).toLocaleTimeString(),
    },
    {
        id: uuidv4(),
        name: 'Some one with a good name',
        description: 'This is a transcation from from some day',
        items: 10,
        length: 5,
        unitPrice: 100,
        cost: 3000,
        date: new Date().toDateString(),
        time: (new Date()).toLocaleTimeString(),
    },
    {
        id: uuidv4(),
        name: 'Some one with a good name',
        description: 'This is a transcation from from some day',
        items: 10,
        length: 5,
        unitPrice: 100,
        cost: 3000,
        date: new Date().toDateString(),
        time: (new Date()).toLocaleTimeString(),
    },
    {
        id: uuidv4(),
        name: 'Some one with a good name',
        description: 'This is a transcation from from some day',
        items: 10,
        length: 5,
        unitPrice: 100,
        cost: 3000,
        date: new Date().toDateString(),
        time: (new Date()).toLocaleTimeString(),
    },
    {
        id: uuidv4(),
        name: 'Some one with a good name',
        description: 'This is a transcation from from some day',
        items: 10,
        length: 5,
        unitPrice: 100,
        cost: 3000,
        date: new Date().toDateString(),
        time: (new Date()).toLocaleTimeString(),
    },
    {
        id: uuidv4(),
        name: 'Some one with a good name',
        description: 'This is a transcation from from some day',
        items: 10,
        length: 5,
        unitPrice: 100,
        cost: 3000,
        date: new Date().toDateString(),
        time: (new Date()).toLocaleTimeString(),
    },
    {
        id: uuidv4(),
        name: 'Some one with a good name',
        description: 'This is a transcation from from some day',
        items: 10,
        length: 5,
        unitPrice: 100,
        cost: 3000,
        date: new Date().toDateString(),
        time: (new Date()).toLocaleTimeString(),
    },
    {
        id: uuidv4(),
        name: 'Transaction number 1',
        description: 'This is a transcation from from some day',
        items: 10,
        length: 5,
        unitPrice: 100,
        cost: 3000,
        date: new Date().toDateString(),
        time: (new Date()).toLocaleTimeString(),
    },
    {
        id: uuidv4(),
        name: 'Some one with a good name',
        description: 'This is a transcation from from some day',
        items: 10,
        length: 5,
        unitPrice: 100,
        cost: 3000,
        date: new Date().toLocaleDateString(),
        time: (new Date()).toLocaleTimeString(),
    },
]



export const stock = [
    {
        id: uuidv4(),
        name: 'Plywood',
        unitPrice: 45,
    },
    {
        id: uuidv4(),
        name: 'Aluzinc Special',
        unitPrice: 785,
    },
    {
        id: uuidv4(),
        name: 'Paint box',
        unitPrice: 100,
    },
    {
        id: uuidv4(),
        name: 'Box of nails',
        unitPrice: 12,
    },
]